spring:
  application:
    name: ProductService
  datasource:
    url: ${PRODUCT_SERVICE_DB_URL}
    username: ${PRODUCT_SERVICE_DB_USERNAME}
    password: ${PRODUCT_SERVICE_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
logging:
  level:
    org.springframework.web: debug
server:
  port: ${PRODUCT_SERVICE_PORT}

# eureka configuration
eureka.client.register-with-eureka: true
eureka.client.fetch-registry: true
# if eureka server is running on default port number 8761 then no need to specify serviceUrl
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
